stages:
  run_asr:
    cmd: poetry run python pipeline/02-run_asr.py
    deps:
      - data/raw/yt_metadata
      - src/processing/whisper_pipeline.py
      - pipeline/02-run_asr.py
    outs:
      - data/interim/audio_transcripts_v3_large.parquet.gzip
  tokenize_transcripts:
    cmd: poetry run python pipeline/03-tokenize_transcripts.py
    deps:
      - data/interim/audio_transcripts_v3_large.parquet.gzip
      - src/processing/transcript_cleaner.py
      - pipeline/03-tokenize_transcripts.py
    outs:
      - data/interim/sentences.parquet.gzip
  run_popbert:
    cmd: poetry run python pipeline/04-run_popbert.py
    deps:
      - data/interim/sentences.parquet.gzip
      - src/processing/popbert_predictor.py
      - pipeline/04-run_popbert.py
    outs:
      - data/interim/popbert.parquet.gzip
  run_manifesto_roberta:
    cmd: poetry run python pipeline/05-run_manifesto_roberta.py
    deps:
      - data/interim/sentences.parquet.gzip
      - src/processing/manifesto_predictor.py
      - pipeline/05-run_manifesto_roberta.py
    outs:
      - data/interim/manifesto_roberta.parquet.gzip
  basic_descriptives:
    cmd: poetry run papermill pipeline/06-basic_descriptives.ipynb reports/notebooks/06-basic_descriptives.ipynb
    deps:
      - src/load/
      - data/interim/popbert.parquet.gzip
      - data/interim/sentences.parquet.gzip
      - data/raw/yt_metadata/
    outs:
      - reports/notebooks/06-basic_descriptives.ipynb
      - reports/tables/dataset_summary.csv
      - reports/figures/view_count_violin_vertical.pdf
      - reports/figures/view_count_violin_vertical.svg
      - reports/figures/view_count_violin.pdf
      - reports/figures/view_count_violin.svg
  nb_regression:
    cmd: Rscript -e "rmarkdown::render('pipeline/07-nb_regression.Rmd', 'html_document', '../reports/notebooks/07-nb_regression.html')"
    deps:
      - src/load/
      - data/interim/popbert.parquet.gzip
      - data/interim/sentences.parquet.gzip
      - data/raw/yt_metadata/
    outs:
      - reports/notebooks/07-nb_regression.html
      - reports/figures/nb_regression_like_count.pdf
      - reports/figures/nb_regression_like_count.svg
      - reports/figures/nb_regression_like_count_vertical.pdf
      - reports/figures/nb_regression_like_count_vertical.svg
