---
title: "Untitled"
output: html_document
date: "2024-02-06"
---

# Load data

```{r setup, include=T}
library(here)

knitr::opts_chunk$set(echo = TRUE)
options(box.path = here())

box::use(
  r / load
)
box::reload(load)

library(tidyverse)
# library(marginaleffects)
# library(ggeffects)
# library(ggpubr)
library(quantreg)

theme_set(theme_minimal())

colormap <- load$colormap()

PLOT_WIDTH <- 10
PLOT_HEIGHT <- 8

z_transform <- function(x) as.vector(scale(x))

df <- load$regression_data()

df <- df |>
  group_by(channel) |>
  mutate(
    d_elite = elite,
    elite = z_transform(elite),
    d_pplcentr = pplcentr,
    pplcentr = z_transform(pplcentr)
  ) |>
  # ungroup() |>
  # group_by(party) |>
  # mutate(
  #   # log_video_likes = z_transform(log_video_likes),
  #   log_video_views = z_transform(log_video_views)
  # ) |>
  ungroup()

```

# show descriptives

```{r}
df_summary <- df |>
  group_by(party) |>
  summarize(
    n = n(),
    elite_mean = mean(d_elite),
    elite_sd = sd(d_elite),
    pplcentr_mean = mean(d_pplcentr),
    pplcentr_sd = sd(d_pplcentr),
    n_sents_mean = mean(n_sents),
    n_sents_sd = sd(n_sents)
  )

df_summary_long <- df_summary |>
  tidyr::pivot_longer(
    cols = c(elite_mean, elite_sd, pplcentr_mean, pplcentr_sd),
    names_to = c("var", ".value"),
    names_pattern = "(elite|pplcentr)_(mean|sd)"
  )

print(df_summary, n=100)
```


```{r}
parties <- df |> pull(party) |> unique()
quantiles = seq(0.75, 0.99, by=0.01)
elite_form <- formula(
  log_video_views ~ log_n_sents + released_year + is_short * elite + channel
)

extract_coefs <- function(model) {
  taus <- as.numeric(sub("tau= ", "", colnames(model$coefficients)))

  df <- model$coefficients %>%
    t() %>%
    as_tibble()
  df$tau <- model$tau

  df <- df %>%
    setNames(gsub("TRUE$|1$", "", names(.))) %>%
    rename(Intercept = `(Intercept)`)

  return(df)
}

results <- list()
i <- 0
for (party in parties) {
  print(party)
  reg_df <- df |>
    drop_na(video_views) |>
    filter(party == !!party) |>
    mutate(
      channel = channel |> fct_drop(),
      party = party |> fct_drop()
    )

  for (q in quantiles) {
    print(paste(party, q))
    model <- quantreg::rq(elite_form, data=reg_df, tau=quantiles, method="sfn")
  }


  # coefs <- extract_coefs(model)
  # coefs$party <- party
  # i <- i + 1
  # results[[i]] <- coefs
}
# all_coefs <- results |> bind_rows()
```


```{r, eval=F}
ggplot(all_coefs, aes(x=tau, y=elite)) +
  geom_line() +
  facet_wrap(~party, ncol=2, scales="free")
```
