---
title: "Untitled"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
library(here)

knitr::opts_chunk$set(echo = TRUE)
options(box.path = here())

box::use(
  r / load
)
box::reload(load)

library(tidyverse)
library(marginaleffects)
library(ggeffects)
library(ggpubr)

theme_set(theme_minimal())

z_transform <- function(x) as.vector(scale(x))

df <- load$regression_data() |>
  group_by(channel) |>
  mutate(
    views = log(video_views),
    likes = log1p(video_likes),
    d_elite = elite,
    # elite = z_transform(elite),
    # elite = elite - mean(elite),
    d_pplcentr = pplcentr,
    # pplcentr = pplcentr - mean(pplcentr)
    # pplcentr = z_transform(pplcentr)
  ) |>
  ungroup()
```


# show descriptives

```{r}
df |>
  group_by(channel) |>
  summarize(
    n = n(),
    elite_mean = mean(d_elite),
    elite_sd = sd(d_elite),
    pplcentr_mean = mean(d_pplcentr),
    pplcentr_sd = sd(d_pplcentr),
  ) |> print(n=100)
```

# NB Regression on Video Views

```{r}
channels <- df |> select(channel) |> pull() |> unique()

grid_vals <- list(
  seq(0, 0.8, 0.01)
)

elite_form <- formula(
  views ~ elite + released_year
)

pplcentr_form <- formula(
  views ~ pplcentr + released_year
)

elite_preds 1- list()
pplcentr_preds <- list()
i <- 0

for (channel in channels) {
  i <- i + 1

  df_channel <- df  |> filter(channel==!!channel)

  elite_model <- lm(elite_form, data = df_channel)

  predictions <- marginaleffects::slopes(
    model = elite_model,
    by = c("released_year", "elite"),
    newdata = df_channel,
    # newdata = marginaleffects::datagrid(
    #   model = elite_model,
    #   newdata = df_channel
    # )
    ) |> mutate(
      channel = !!channel
    )

  elite_preds[[i]] = predictions

  pplcentr_model <- lm(pplcentr_form, data = df_channel)

  predictions <- marginaleffects::slopes(
    model = pplcentr_model,
    by = c("released_year", "pplcentr"),
    newdata = df_channel,
  ) |> mutate(
    channel = !!channel
  )

  pplcentr_preds[[i]] = predictions

}
```

```{r}
df_elite <- elite_preds |>
  bind_rows() |>
  rename(popvar = elite) |>
  mutate(var = "elite")

df_pplcentr <- pplcentr_preds |>
  bind_rows() |>
  rename(popvar = pplcentr) |>
  mutate(var = "pplcentr")

df_pred <- df_elite |> bind_rows(df_pplcentr)
```

```{r}
ggplot(df_pred, aes(x=popvar, y=estimate, color=var)) +
  geom_smooth() +
  facet_wrap(~channel, scales="free_y")
```
```{r}
create_plot <- function(model, predictor) {

  grid_vals <- list(
    c(-0.1, -0.05, 0, 0.05, 0.1, 0.2, 0.3 )
  )
  names(grid_vals) <- predictor
  marginaleffects::plot_predictions(
      model,
      by = c("channel", predictor),
      transform = exp,
      newdata = marginaleffects::datagrid(
        pplcentr = seq(0, 0.8, 0.02)
      )
    ) +
    coord_flip() +
    theme_ggeffects(base_family = "serif")
}

elite_plot <- create_plot(elite_model, "elite")
pplcentr_plot <- create_plot(pplcentr_model, "pplcentr")

ggarrange(elite_plot, pplcentr_plot, ncol = 1)
```

# NB Regression on Video Likes

```{r}
elite_form <- formula(
  likes ~ channel + elite + channel:elite + released_year + channel:released_year + video_duration
)

elite_model <- glm.nb(elite_form, data = df)
summary(elite_model)
```

```{r}
pplcentr_form <- formula(
  likes ~ channel + pplcentr + channel:pplcentr + released_year + channel:released_year + video_duration
)

pplcentr_model <- glm.nb(pplcentr_form, data = df)
summary(pplcentr_model)
```

```{r}
elite_plot <- marginaleffects::plot_predictions(
    elite_model,
    condition = list("channel", "elite" = "quartile")
  ) +
  coord_flip() +
  theme_ggeffects(base_family = "serif")

pplcentr_plot <- marginaleffects::plot_predictions(
    pplcentr_model,
    condition = list("channel", "pplcentr" = "quartile")
  ) +
  coord_flip() +
  theme_ggeffects(base_family = "serif")

ggarrange(elite_plot, pplcentr_plot, ncol = 1)
```

```{r}
p <- here("reports", "figures", "nb_regression_like_count.svg")
if (file.exists(p)) file.remove(p)
ggsave(p, width = 7, height = 5)
```

```{r}
# df |>
#   select(video_views, channel, elite, year, video_duration) |>
#   group_by(channel) |>
#   summarize(across(everything(), ~ is.na(.) |> sum()))
```
```{r}
# elite_form <- formula(
#   video_views ~ channel + elite + channel*elite + year + video_duration
# )

# elite_model <- glm.nb(elite_form, data = df)
# summary(elite_model)
```

```{r}
# pplcentr_form <- formula(
#   video_views ~ channel + pplcentr + channel:pplcentr + year + video_duration
# )

# pplcentr_model <- glm.nb(pplcentr_form, data = df)
# summary(pplcentr_model)
```

```{r}
# elite_plot <- sjPlot::plot_model(
#   elite_model,
#   type = "eff",
#   terms = c("channel", "elite [-1,0,1]")
# ) +
#   coord_flip() +
#   labs(
#     title = "Marginal Effects of Anti-Elitism",
#     x = "Channel",
#     y = "Number of Views",
#     color = "Anti-Elitism\n(standardized)"
#   ) +
#   theme_ggeffects(base_family = "serif")

# pplcentr_plot <- sjPlot::plot_model(
#   pplcentr_model,
#   type = "eff",
#   terms = c("channel", "pplcentr [-1,0,1]")
# ) +
#   coord_flip() +
#   labs(
#     title = "Marginal Effects of People-Centrism",
#     x = "Channel",
#     y = "Number of Views",
#     color = "People-Centrism\n(standardized)"
#   ) +
#   theme_ggeffects(base_family = "serif")

# ggarrange(elite_plot, pplcentr_plot, ncol = 1)
```

```{r}
# ggsave(here("reports", "figures", "nb_regression_view_count.svg"), width = 7, height = 5)
```
