---
title: "Multi-level Regression"
output:
  html_document:
    number_sections: true
date: "2025-02-04"
---

```{r setup, include=FALSE}
library(here)

knitr::opts_chunk$set(echo = TRUE)
options(box.path = here())

box::use(
  r / load
)
box::reload(load)

library(tidyverse)
library(texreg)
library(ggeffects)
library(ggpubr)

library(lme4)
library(marginaleffects)
library(sjstats)

theme_set(theme_minimal())

channels <- load$channels()
videos <- load$videos(filtered = TRUE)
sentences <- load$sentences(filtered = TRUE)
popbert <- load$popbert(filtered = TRUE)

df_sents <- sentences |>
  left_join(popbert, by = "sentence_id") |>
  group_by(video_id) |>
  summarize(
    elite = mean(elite),
    pplcentr = mean(pplcentr)
  )

```

```{r}
z_transform <- function(x) as.vector(scale(x))

df <- channels |>
  left_join(videos, by = "channel_id") |>
  left_join(df_sents, by = "video_id") |>
  mutate(
    channel = factor(channel)
  )

df <- df %>%
  mutate(
    year = video_uploadtime |> lubridate::year() |> as_factor(),
    channel = channel |> as_factor()
  ) %>%
  group_by(channel) %>%
  mutate(
    # elite = z_transform(elite),
    # pplcentr = z_transform(pplcentr),
  ) %>%
  ungroup()

df_likes <- df |>
  filter(channel != "FDP") |>
  mutate(channel = channel |> as_factor() |> fct_drop())

df_views <- df |>
  mutate(channel = channel |> as_factor() |> fct_drop())
```

```{r}
df_views |>
  group_by(channel) |>
  summarize(
      n = n(),
      mean_likes = mean(video_likes),
      mean_views = mean(video_views),
      std_views = sd(video_views)
    )
```

# Video Views

## Simplest linear model

```{r}
model <- lm(
  formula = video_views ~ 1,
  data = df_views
)
screenreg(model)
```

## Multlevel Null Model

```{r}
model <- lme4::lmer(
  formula = video_views ~ 1 + (1 | channel),
  data = df_views
)
screenreg(model)
```

```{r}
performance::icc(model)
```

## Full Model

```{r}
model <- lme4::lmer(
  formula = video_views ~ elite + video_duration + year + (year | channel),
  data = df_views
)
screenreg(model)
```

```{r}
fixef(model)
```

```{r}
ranef(model)
```


```{r}
performance::icc(model)
```

# Video Likes
## Model

```{r}
model <- lme4::lmer(
  formula = video_likes ~ 1 + (1 | channel),
  data = df_likes
)
screenreg(model)
```

```{r}
performance::icc(model)
```
